name: electrical_load_calculator
description: A Flutter app to calculate electrical load and track history
publish_to: "none" # Remove this line if you want to publish

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6

  # Local storage
  shared_preferences: ^2.2.2

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/l10n/

  # (Optional) Fonts example
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf